import type { Metadata } from "next";
import Link from "next/link";
import { CaseStudySection } from "@/components/case-study-section";
import { CaseStudyPasswordGate } from "@/components/case-study-password-gate";
import { isCowbellCaseStudyUnlocked } from "@/lib/case-study-auth";

export const metadata: Metadata = {
  title: "Design System as a Service",
  description:
    "A password-protected case study on building an AI-readable design system at a cyber insurance platform.",
};

export default async function CowbellDesignSystemPage() {
  const unlocked = await isCowbellCaseStudyUnlocked();

  if (!unlocked) {
    return <CaseStudyPasswordGate title="Design System as a Service" />;
  }

  return (
    <article className="page-wrap py-16 md:py-24">
      <header className="read-width">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-foreground/70">
          Private case study · Cowbell
        </p>
        <h1 className="mt-3 text-3xl font-semibold tracking-tight text-foreground md:text-4xl lg:text-[2.75rem]">
          Design System as a Service
        </h1>
        <p className="mt-3 max-w-2xl text-sm font-medium text-muted-foreground/90 md:text-[15px]">
          Design system strategy · AI tooling · Cowbell console
        </p>
        <p className="mt-6 max-w-2xl text-lg font-medium leading-relaxed text-muted-foreground md:text-xl md:leading-relaxed">
          I own the plan to turn two years of undocumented design decisions
          into a token pipeline and a set of AI-readable rules files — so
          that Claude, Cursor, and the engineers using them generate
          on-brand UI by default instead of guessing.
        </p>
        <p className="mt-6 max-w-2xl text-sm leading-relaxed text-muted-foreground">
          This is real, active strategy work at Cowbell. Names of specific
          coworkers are omitted out of respect for their privacy; the
          decisions, tools, and outcomes below are unedited.
        </p>
      </header>

      <div className="mt-24 space-y-24 md:mt-32 md:space-y-28">
        <CaseStudySection title="The problem">
          <p>
            Cowbell&apos;s console runs on Mantine as its component library,
            with brand colors defined in a Figma design library — but the
            console itself is still largely built on a legacy library, MUI,
            and looks inconsistent as a result. For two years, design and
            code had drifted: custom colors lived in Figma but weren&apos;t
            reliably in code, and when anyone building UI needed a decision
            — a color, a spacing rule, which component to use — they were
            guessing, because the system&apos;s decisions weren&apos;t
            written down anywhere that survives interpretation.
          </p>
          <p>
            AI tooling made the gap more urgent, not less. The core insight
            driving this plan: AI doesn&apos;t replace the need for a design
            system — it raises the cost of not having a good one.
            Undocumented decisions don&apos;t just confuse a new hire
            anymore; they get filled in confidently and incorrectly by an
            AI tool, at scale, across every session that doesn&apos;t have
            the real context loaded.
          </p>
        </CaseStudySection>

        <CaseStudySection title="The plan">
          <p>
            I structured the work in four phases, each one a prerequisite
            for the next. <strong className="font-semibold text-foreground">Foundation</strong>{" "}
            gets the actual color and spacing decisions out of Figma and
            into code as CSS custom properties, generated by an existing
            internal token pipeline rather than hand-copied — so there is
            one source of truth instead of two that drift.{" "}
            <strong className="font-semibold text-foreground">
              AI-readable
            </strong>{" "}
            is the layer most design systems skip: a Claude Skill and an
            always-on rules file (AGENTS.md) that package the token
            architecture, component specs, and anti-patterns so every AI
            session starts with Cowbell&apos;s actual system loaded, instead
            of the model inventing its own defaults.{" "}
            <strong className="font-semibold text-foreground">
              Migration
            </strong>{" "}
            retires the legacy MUI code page by page, as side work, using
            that same AI context to make the rewrites faster and more
            consistent than a manual migration would be.{" "}
            <strong className="font-semibold text-foreground">
              Service layer
            </strong>{" "}
            is the part that actually makes adoption stick — a single
            owner, an intake channel, and a decision framework for edge
            cases, because the research is consistent that documentation
            alone doesn&apos;t drive adoption; someone being reachable does.
          </p>
          <p>
            Token naming was a deliberate early decision, not an
            afterthought: a token named for a raw value (a shade of blue) is
            something a person or a model can only guess about, while a
            token named for its intent (the color for a primary action) is
            something they can reason over. That distinction is what makes
            a system machine-readable instead of just organized.
          </p>
        </CaseStudySection>

        <CaseStudySection title="Choosing pragmatism over a clean rewrite">
          <p>
            Partway through, I made the case for reconsidering Mantine
            itself. It has no official Figma component library — only an
            unmaintained community kit — and its theming system stops at
            alias-level tokens with no native semantic layer, which meant a
            chunk of Figma&apos;s own token structure had nowhere to land
            in code. I evaluated three alternatives against it, ran
            Cowbell&apos;s brand blue through each one&apos;s token tooling
            to check the color mapping held up, and brought a real
            comparison — not a preference — to the team that owned the
            decision.
          </p>
          <p>
            The team decided to stay on Mantine. Given how much of the
            console was already built against it, a library switch would
            have meant migrating twice. Instead, a separate AI-powered
            design-to-code tool was adopted as the bridge between Figma and
            Mantine, closing most of the gap the evaluation had surfaced
            without requiring the rewrite. I still think the structural
            critique of Mantine was correct — but the pragmatic call was
            the right one for where the console actually was.
          </p>
        </CaseStudySection>

        <CaseStudySection title="Proof of concept, not a promise">
          <p>
            Before committing further investment, I designed a three-day
            test: give an AI tool Cowbell&apos;s real token pipeline and a
            skill file describing the system, then run identical prompts —
            build a primary button, build a settings section — with and
            without that context loaded. The test isn&apos;t whether the
            full system is perfect; it&apos;s whether the with/without
            difference is obvious enough to justify the rest of the plan. A
            published study on a comparable agentic design system reported
            accuracy rising from 65% to 100% and variance dropping by
            99.9% with the equivalent infrastructure in place — a
            reasonable bar to test against, not to assume.
          </p>
        </CaseStudySection>

        <CaseStudySection title="A real build, not a hypothetical">
          <p>
            The clearest evidence the approach works came from a real
            feature build, not a staged demo. An engineer asked for a
            persona-specific mega menu modeled on an existing pattern
            elsewhere in the codebase. Claude built it on a branch,
            matching the existing component and internationalization
            conventions by reading the codebase rather than being told the
            rules from scratch — the same six-locale translation pattern
            already in use stayed in sync automatically, without an
            explicit instruction to keep it that way.
          </p>
          <p>
            I tested it locally and reported the only visible problem in
            plain language — dark mode was broken, light mode was fine, no
            diagnosis attached. Claude traced it to a background token
            tuned for cards layered over a solid page, at an opacity that
            let the dashboard behind the menu bleed through once it
            rendered in a portal, and fixed it by swapping to an opaque
            token meant for exactly that context. A second automated
            reviewer, checking the same change independently, caught a
            related issue the first fix hadn&apos;t touched — the
            popover&apos;s portal wasn&apos;t scoped to the right theme
            container, a second layer of the same theming risk.
          </p>
          <p>
            That loop — a person testing in plain language, an AI tool
            inferring conventions instead of having them restated, a second
            independent check catching what the first pass missed — is
            exactly the workflow the AI-readable phase of the plan is
            trying to formalize for everyone working in the codebase, not
            just for one branch.
          </p>
        </CaseStudySection>

        <CaseStudySection title="Design decisions">
          <div className="space-y-8 md:space-y-9">
            <div>
              <h3 className="text-base font-semibold text-foreground">
                Undocumented decisions are worse with AI, not neutral
              </h3>
              <p className="mt-2">
                Before AI tooling, an ambiguous design decision meant one
                engineer occasionally guessed wrong. With AI tooling, an
                ambiguous decision means every session guesses wrong,
                confidently, at whatever scale the tool gets used. That
                reframing is what justified prioritizing the AI-readable
                layer instead of treating it as a nice-to-have on top of a
                token pipeline.
              </p>
            </div>
            <div>
              <h3 className="text-base font-semibold text-foreground">
                Prove it in three days before funding four phases
              </h3>
              <p className="mt-2">
                A plan this size is easy to over-invest in before knowing
                whether the core mechanism even works. Scoping a small,
                falsifiable test first — with a stated definition of what
                passing looks like — meant the bigger commitment only
                happened once there was evidence behind it.
              </p>
            </div>
            <div>
              <h3 className="text-base font-semibold text-foreground">
                A structural critique doesn&apos;t have to win the decision
              </h3>
              <p className="mt-2">
                I brought real trade-off data to the Mantine-versus-alternatives
                decision and the team still chose the pragmatic path over
                the technically cleaner one. Documenting the critique
                anyway — rather than letting the decision erase it — means
                the limitation is on record for when it&apos;s worth
                revisiting instead of getting rediscovered from scratch.
              </p>
            </div>
            <div>
              <h3 className="text-base font-semibold text-foreground">
                Name tokens for intent, not for value
              </h3>
              <p className="mt-2">
                This is the single decision the rest of the AI-readability
                work depends on. A value-based name can only be looked up;
                an intent-based name can be reasoned about — by a person
                skimming the system for the first time or a model
                generating new UI from it.
              </p>
            </div>
          </div>
        </CaseStudySection>

        <CaseStudySection title="Status">
          <ul className="list-none space-y-3 pl-0 text-[15px] font-medium leading-snug md:text-base">
            <li>
              This is active, in-progress work — not a finished rollout.
              The token pipeline and library decision are settled; the
              rules files are drafted and in review; the migration and
              service-layer phases are ahead.
            </li>
            <li>
              The mega-menu build is the first real evidence the
              AI-readable approach holds up outside a controlled test —
              a genuine feature, built by an engineer&apos;s request, with
              real bugs caught and fixed through the intended feedback
              loop.
            </li>
            <li>
              The three-day proof-of-concept is designed to be the gate
              before further investment — a deliberately small, falsifiable
              test ahead of a four-phase commitment, not after one.
            </li>
          </ul>
        </CaseStudySection>
      </div>

      <div className="read-width mt-28 md:mt-36 space-y-8">
        <p>
          <Link
            href="/"
            className="text-base font-semibold text-foreground underline decoration-muted-foreground underline-offset-[6px] transition-colors hover:decoration-foreground"
          >
            Back home
          </Link>
        </p>
      </div>
    </article>
  );
}
